### ISSUE TITLE
Build failed 

### ISSUE THREAD

**Issue by rohitist** [mapr/libhbase#4]
First attempt to build libhbase failed with the following log:

``` [INFO]
[INFO] --- maven-antrun-plugin:1.7:run (build-libhbase-binaries) @ libhbase ---
[INFO] Executing tasks
main:
     [echo] Building libHBase...
     [exec] Downloading http://services.gradle.org/distributions-snapshots/gradle-1.12-  20140310230028+0000-bin.zip
     [exec] Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: http://downloads.gradle.org/distributions-snapshots/gradle-1.12-20140310230028+0000-bin.zip
     [exec]     at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)
     [exec]     at org.gradle.wrapper.Install.createDist(Install.java:44)
     [exec]     at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
     [exec]     at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:55)
     [exec] Caused by: java.io.FileNotFoundExcep
     [exec] tion: http://downloads.gradle.org/distributions-snapshots/gradle-1.12-20140310230028+0000-bin.zip
     [exec]     at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1624)
     [exec]     at org.gradle.wrapper.Download.downloadInternal(Download.java:56)
     [exec]     at org.gradle.wrapper.Download.download(Download.java:42)
     [exec]     at org.gradle.wrapper.Install$1.call(Install.java:57)
     [exec]     at org.gradle.wrapper.Install$1.call(Install.java:44)
     [exec]     at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
     [exec]     ... 3 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

So, I went to the gradle site and tried to locate the file `gradle-1.12-20140310230028+0000-bin.zip` but unfortunately it was not there. I replaced the file name in the file `gradle-wrapper.properties` with the latest file available `gradle-2.3-20141215231546+0000-bin.zip`. 
Next attempt of build ran past to this stage but failed with a different error shown below:

`[exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * Where:
     [exec] Build file '/home/rohit/Downloads/libhbase-master/build.gradle' line: 120
     [exec] 
     [exec] * What went wrong:
     [exec] A problem occurred evaluating root project 'libhbase-master'.
     [exec] > Could not find method hbase() for arguments [build_e5rqym7rzc0lqki4a04q5cja8$_run_closure5_closure23@5a632bc3] on root project 'libhbase-master'.
     [exec] 
     [exec] * Try:
     [exec] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
     [exec] Found JAVA_HOME: /usr/lib/jvm/java-7-openjdk-amd64
     [exec] 
     [exec] BUILD FAILED
     [exec] 
     [exec] Total time: 2 mins 27.738 secs
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------`

Please help to fix this issue.

**Comment by pwong-mapr** [comment]
Fixed by this commit: https://github.com/mapr/libhbase/commit/c91d5728c29a57ccf65cbc4ebe7d376c2014da21

**Comment by rohitist** [comment]
Thanks for the commit. But the build failed with a new error. 

```
[exec] :linkPerftestExecutable FAILED
     [exec] 
     [exec] BUILD FAILED
     [exec] 
     [exec] Total time: 1 mins 45.149 secs
     [exec] /usr/bin/ld: /home/rohit/Downloads/libhbase-c91d5728c29a57ccf65cbc4ebe7d376c2014da21/target/gradle/objectFiles/perftestExecutable/perftestCpp/1vehhllu93v2vis5onm5ac53md/test_types.o: undefined reference to symbol 'sem_getvalue@@GLIBC_2.2.5'
     [exec] //lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
     [exec] collect2: error: ld returned 1 exit status
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':linkPerftestExecutable'.
     [exec] > Linker failed; see the error output for details.
     [exec] 
[exec] * Try:
     [exec] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:55.529s
[INFO] Finished at: Wed Dec 17 10:53:49 IST 2014
[INFO] Final Memory: 18M/167M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (build-libhbase-binaries) on project libhbase: An Ant BuildException has occured: exec returned: 1
[ERROR] around Ant part ...<exec dir="/home/rohit/Downloads/libhbase-c91d5728c29a57ccf65cbc4ebe7d376c2014da21" executable="bash" failonerror="true">... @ 5:124 in /home/rohit/Downloads/libhbase-c91d5728c29a57ccf65cbc4ebe7d376c2014da21/target/antrun/build-main.xml
[ERROR] -> [Help 1]

```

The gcc version installed on my machine is: `4.8.2`.

Please suggest.

**Comment by adityakishore** [comment]
I have back-ported a commit from 0.98.x branch. Please update the repository and retry.

The commit 0ddda015113452955ed600116f58a47eebe3b24a should fix this.

**Comment by rohitist** [comment]
Thanks Aditya. Problem solved. :)

**Comment by adityakishore** [comment]
Good to know :) Do let us know if you run into any more issues.

Would you mind sharing your use case that you are trying to solve with libhbase?

**Comment by rohitist** [comment]
Sure Aditya bhai........ My use case is very simple. I need to gather region name regarding a value from hbase. I have two information with me, viz, tableName and value which would be used to get the region name. I am sure you already know how to get this information. 
I have not tried your API to get these information yet, because I am first learning the java API to understand things first. I will let you know how libhbase API works with my project.
