### ISSUE TITLE
Cannot compile "example_async.c"

### ISSUE THREAD

**Issue by rohitist** [mapr/libhbase#5]
I am not an expert in C/C++. So, I could not figure out what compiler option is missing here.
While trying to compile `example_async.c` using following command:

`gcc -std=gnu99 -Itarget/libhbase-1.0-SNAPSHOT/include/ -Isrc/test/native/common/ /usr/lib/hbase/libhbase-master/target/libhbase-1.0-SNAPSHOT/lib/native/libhbase.so /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.45.x86_64/jre/lib/amd64/server/libjvm.so example_async.c`

I get following error messages:

`
/tmp/cc9hmnRP.o: In function `release_row_data':
example_async.c:(.text+0x59): undefined reference to `bytebuffer_free'
example_async.c:(.text+0x9f): undefined reference to `bytebuffer_free'
/tmp/cc9hmnRP.o: In function `get_callback':
example_async.c:(.text+0x5a3): undefined reference to `bytebuffer_strcpy'
example_async.c:(.text+0x6d6): undefined reference to `bytebuffer_free'
example_async.c:(.text+0x72f): undefined reference to `bytebuffer_free'
/tmp/cc9hmnRP.o: In function `main':
example_async.c:(.text+0x127f): undefined reference to `bytebuffer_strcpy'
example_async.c:(.text+0x1290): undefined reference to `bytebuffer_strcpy'
example_async.c:(.text+0x15dc): undefined reference to `bytebuffer_printf'
example_async.c:(.text+0x168b): undefined reference to `bytebuffer_printf'
example_async.c:(.text+0x1861): undefined reference to `bytebuffer_printf'
example_async.c:(.text+0x18ec): undefined reference to `bytebuffer_printf'
example_async.c:(.text+0x19ec): undefined reference to `bytebuffer_printf'
/tmp/cc9hmnRP.o:example_async.c:(.text+0x1b6f): more undefined references to `bytebuffer_printf' follow
/tmp/cc9hmnRP.o: In function `main':
example_async.c:(.text+0x1de5): undefined reference to `bytebuffer_strcpy'
example_async.c:(.text+0x1edb): undefined reference to `bytebuffer_strcpy'
example_async.c:(.text+0x1fae): undefined reference to `bytebuffer_strcpy'
example_async.c:(.text+0x2140): undefined reference to `bytebuffer_free'
example_async.c:(.text+0x2159): undefined reference to `bytebuffer_free'
collect2: ld returned 1 exit status
`

After linking following object at the end of the above mentioned gcc command, I got the code compiled successfully.

`./target/gradle/objectFiles/perftestExecutable/perftestCpp/33pqpat9eh4ag2l6esp3eecndu/byte_buffer.o`

But when I run the executable, I get the following error:

`./a.out: error while loading shared libraries: libhbase.so: cannot open shared object file: No such file or directory`

Please enlighten me.

**Comment by rohitist** [comment]
OK. I solved the compile and run issue by myself. 

I added following lines in `/etc/ld.so.conf` file:

`
/usr/lib/hbase/libhbase-master/target/gradle/binaries/hbaseSharedLibrary
/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.45.x86_64/jre/lib/amd64/server
`

And then `ldconfig`.
And, `export HBASE_CONF_DIR=/usr/lib/hbase/hbase-0.98.7-hadoop2/conf`
And at last, `export HBASE_LIB_DIR=/usr/lib/hbase/hbase-0.98.7-hadoop2/lib`.

Compiled and Ran.
I got some exceptions, such as `Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/jni/ClientProxy` but will post an another issue, if I could not resolve by myself.

Closing.

**Comment by kewang** [comment]
I have the same issue, but I try to your steps and still error.
